blank_issues_enabled: false
contact_links:
  - name: Security advisories
    url: https://github.com/FJrodafo/FJrodafo.github.io/security/advisories
    about: Please report security vulnerabilities here.
